basePath: /
info:
  contact:
    email: justine.bachelard@ext.uca.fr
    name: Justine Bachelard.
  description: API to manage songs.
  title: middleweare
  version: 1.0.0
paths: {}
schemes:
- http
swagger: "2.0"
